FROM golang:1.22-alpine

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia o arquivo de código fonte para o container
COPY main.go .

# Expõe a porta 8080 que o servidor utiliza
EXPOSE 8080