export const HTTP_STATUS_CODES = [
  { code: '', description: 'Selecione um Status Code' },
  { code: '100', description: 'Continue' },
  { code: '101', description: 'Switching Protocols' },
  { code: '200', description: 'OK' },
  { code: '201', description: 'Created' },
  { code: '202', description: 'Accepted' },
  { code: '203', description: 'Non-Authoritative Information' },
  { code: '204', description: 'No Content' },
  { code: '205', description: 'Reset Content' },
  { code: '206', description: 'Partial Content' },
  { code: '300', description: 'Multiple Choices' },
  { code: '301', description: 'Moved Permanently' },
  { code: '302', description: 'Found' },
  { code: '303', description: 'See Other' },
  { code: '304', description: 'Not Modified' },
  { code: '307', description: 'Temporary Redirect' },
  { code: '308', description: 'Permanent Redirect' },
  { code: '400', description: 'Bad Request' },
  { code: '401', description: 'Unauthorized' },
  { code: '402', description: 'Payment Required' },
  { code: '403', description: 'Forbidden' },
  { code: '404', description: 'Not Found' },
  { code: '405', description: 'Method Not Allowed' },
  { code: '406', description: 'Not Acceptable' },
  { code: '408', description: 'Request Timeout' },
  { code: '409', description: 'Conflict' },
  { code: '410', description: 'Gone' },
  { code: '413', description: 'Payload Too Large' },
  { code: '414', description: 'URI Too Long' },
  { code: '415', description: 'Unsupported Media Type' },
  { code: '429', description: 'Too Many Requests' },
  { code: '500', description: 'Internal Server Error' },
  { code: '501', description: 'Not Implemented' },
  { code: '502', description: 'Bad Gateway' },
  { code: '503', description: 'Service Unavailable' },
  { code: '504', description: 'Gateway Timeout' },
];
